#this is a lolz to changlol a keyword on entire directory
puts "les ggs sont cuit."
puts "les pomme aussi"
puts "les ggs sont cuit."
puts "les pomme aussi"
puts "les ggs sont cuit."
puts "les pomme aussi"
puts "les ggs sont cuit."
puts "les pomme aussi"
puts "les ggs sont cuit."
puts "les pomme aussi"
puts "les ggs sont cuit."
puts "les pomme aussi"
puts "les ggs sont cuit."
puts "les pomme aussi"
puts "les ggs sont cuit."
puts "les pomme aussi"
puts "les ggs sont cuit."
puts "les pomme aussi"
puts "les ggs sont cuit."
puts "les pomme aussi"
