#this is a lolz to changlol a keyword on entire directory
puts "les jambons sont cuit."
puts "les jambons aussi"
puts "les jambons sont cuit."
puts "les pomme aussi"
puts "les ggs sont cuitttt."
puts "les pomme aussi"
puts "les ggs sont cuit."
puts "les pomme aussi"
puts "les ggs sont cuit."
puts "les pomme aussi"
puts "les ggs sont cuit."
puts "les pomme aussi"
puts "les ggs sont cuit."
puts "les pomme aussi"
puts "les ggs sont cuit."
puts "les pomme aussi"
puts "les ggs sont cuit."
puts "les pomme aussi"
puts "les ggs sont cuit."
puts "les pomme aussi"
